---
- hosts: all
  vars:
    ROOT_PASSWORD: K0song!n
  gather_facts: no
  tasks:

    - name: try login with password (using out-of-band ssh connection)
      local_action: command sshpass -p {{ ROOT_PASSWORD }} ssh -q -o ConnectTimeout=3 root@{{ inventory_hostname }} 'echo ok'
      ignore_errors: true
      register: exists_user

    - name: ping if above succeeded (using in-band ssh connection)
      remote_user: root
      block:
      - name: set root ssh password
        set_fact:
          ansible_password: "{{ ROOT_PASSWORD }}"
      - name: ping
        ping:
          data: pong
      when: exists_user is success
