---
- name: Enable Root Login
  hosts: all
  become: yes  # Use privilege escalation to become root or another privileged user
  tasks:
    - name: Set Password for the Root User
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"
      vars_prompt:
        - name: root_password
          prompt: "Enter the new root password:"
          private: yes

    - name: Enable Root SSH Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present

    - name: Restart SSH Service
      service:
        name: sshd
        state: restarted
