---
- hosts: all
  become: yes

  tasks:
    - name: Check if curl is installed (Debian-based systems)
      command: dpkg -l | grep curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Check if curl is installed (Red Hat-based systems)
      command: rpm -q curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Install curl (Debian-based systems)
      apt:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'Ubuntu'

    - name: Install curl (Red Hat-based systems)
      yum:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'CentOS'
        
    - name: try login with password (using out-of-band ssh connection)
      local_action: command sshpass -p {{ ROOT_PASSWORD }} ssh -q -o ConnectTimeout=3 root@{{ inventory_hostname }} 'echo ok'
      ignore_errors: true
      register: exists_user

    - name: ping if above succeeded (using in-band ssh connection)
      remote_user: root
      block:
      - name: set root ssh password
        set_fact:
          ansible_password: "{{ ROOT_PASSWORD }}"
      - name: ping
        ping:
          data: pong
      when: exists_user is success
      
    - name: Enable Root SSH Login
      remote_user: root
      block:
      - name: set root ssh password
        set_fact:
          ansible_password: "{{ ROOT_PASSWORD }}"
      
      - name: Replace permit root
        become: yes
        command: sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      
      - name: Restart SSH Service
        become: yes
        service:
         name: sshd
         state: restarted
      - name: Install Python pip
        apt: name={{ item }} update_cache=true state=present force_apt_get=yes
        with_items:
        - python-pip
        - python3-pip
        become: true
      - name: Install Python packages
        pip: name={{ item }}
        with_items:
        - psycopg2-binary
        become: true
      - name: install pexpect
        pip:
         name: pexpect
        become: yes

      - name: set root ssh password
        become: yes
        expect:
         command: passwd
         responses:
          New password: "{{ ROOT_PASSWORD }}"
          Retype new password: "{{ ROOT_PASSWORD }}"
          
    - name: hostname
      shell: hostname
      register: hostname
    - name: Send the output with curl
      shell: |
        curl -X POST -H "Title: ansible task for server {{ hostname.stdout }}" -d "root user login using password allowed" https://ntfy.mmi-pt.com/tes
      #delegate_to: localhost
