- name: Get Disk
  hosts: all
  become: yes
  tasks:
    - name: Install Curl
      when: ansible_pkg_mgr == 'apt'
      apt:
        name: curl
        state: latest
        update_cache: yes

   - name: Install Curl
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: curl
        state: latest
        
    - name: check disk
      shell: df -H | grep -vE "^Filesystem|tmpfs|cdrom|/auto/ripper|loop" | awk '{print $5 " " $6}'
      register: disk_space
    - name: hostname
      shell: hostname
      register: hostname
    - name: Send the output with curl
      shell: |
        curl -X POST -H "Title: Disk status for server {{ hostname.stdout }}" -d "{{ disk_space.stdout }}" https://ntfy.mmi-pt.com/tes
      #delegate_to: localhost
