- name: Get Disk
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes  # This is specific to Debian/Ubuntu. Use 'yum' for Red Hat-based systems.
      when: ansible_os_family == 'Debian'

    - name: Install Curl
      apt:
        name: curl
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Curl
      yum:
        name: curl
        state: present
      when: ansible_os_family == 'RedHat'
      
    - name: check disk
      shell: df -H | grep -vE "^Filesystem|tmpfs|cdrom|/auto/ripper|loop" | awk '{print $5 " " $6}'
      register: disk_space
    - name: hostname
      shell: hostname
      register: hostname
    - name: Send the output with curl
      shell: |
        curl -X POST -H "Title: Disk status for server {{ hostname.stdout }}" -d "{{ disk_space.stdout }}" https://ntfy.mmi-pt.com/tes
      #delegate_to: localhost
