- name: Check Disk Space
  hosts: all
  become: yes
  tasks:
    - name: Run curl command
      command: curl -d https://ntfy.mmi-pt.com/alert
      register: curl_output

    - name: Check disk space
      command: df -h
      register: disk_space

    - name: Display curl output
      debug:
        var: curl_output.stdout_lines

    - name: Display disk space
      debug:
        var: disk_space.stdout_lines
