- name: Get Disk
  hosts: all
  become: yes
  tasks:
    - name: Check if curl is installed (Debian-based systems)
      command: dpkg -l | grep curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Check if curl is installed (Red Hat-based systems)
      command: rpm -q curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Install curl (Debian-based systems)
      apt:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'Ubuntu'

    - name: Install curl (Red Hat-based systems)
      yum:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'CentOS'
        
    - name: check disk
      shell: df -H | grep -vE "^Filesystem|tmpfs|cdrom|/auto/ripper|loop" | awk '{print $5 " " $6}'
      register: disk_space
    - name: hostname
      shell: hostname
      register: hostname
    - name: Send the output with curl
      shell: |
        curl -X POST -H "Title: Disk status for server {{ hostname.stdout }}" -d "{{ disk_space.stdout }}" https://ntfy.mmi-pt.com/tes
      #delegate_to: localhost
