- name: Get Disk
  hosts: all
  become: yes
  tasks:
    - name: check disk
      shell: df -H | grep -vE "^Filesystem|tmpfs|cdrom|/auto/ripper|loop" | awk '{print $5 " " $6}'
      register: disk_space
    - name: hostname
      shell: hostname
      register: hostname
    - name: Send the output with curl
      shell: |
        curl -X POST -d "server {{ hostname.stdout }} Disk avaibility \n{{ disk_space.stdout }}" https://ntfy.mmi-pt.com/tes
      #delegate_to: localhost
