- name: Get Disk
  hosts: all
  become: yes
  tasks:
    - name: Run a command and capture its output
      shell: df -H | grep -vE "^Filesystem|tmpfs|cdrom|/auto/ripper|loop" | awk '{print $5 " " $6}'
      register: disk_space
    - name: Send the output with curl
      shell: |
        curl -X POST -d "{{ disk_space.stdout }}" https://ntfy.mmi-pt.com/tes
      #delegate_to: localhost
