- name: Install server requirement
  hosts: all
  become: yes
  tasks:
    - name: curl
      block:
      - name: Check if curl is installed (Debian-based systems)
        command: dpkg -l | grep curl
        ignore_errors: yes
        register: curl_check
        changed_when: false

      - name: Check if curl is installed (Red Hat-based systems)
        command: rpm -q curl
        ignore_errors: yes
        register: curl_check
        changed_when: false

      - name: Install curl (Debian-based systems)
        apt:
          name: curl
          state: present
        when: curl_check.failed and ansible_distribution == 'Ubuntu'

      - name: Install curl (Red Hat-based systems)
        yum:
          name: curl
          state: present
        when: curl_check.failed and ansible_distribution == 'CentOS'
      - name: Confirm curl installation
        command: >
          curl --version
        register: curlstatus
        changed_when: false
        
    - name: docker & docker compose
      block:
      - name: Check if Docker is installed
        command: dpkg -l | grep -E '^ii' | grep -q docker
        register: docker_installed
        ignore_errors: yes
        changed_when: false

      - name: Update apt package cache
        apt:
          update_cache: yes
        when: docker_installed.failed 
      
      - name: Install required packages
        apt:
          name: "{{ item }}"
          state: present
        loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        when: docker_installed.failed 
      
      - name: Add Docker GPG key
        apt_key:
          id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
          keyserver: hkp://keyserver.ubuntu.com:80
        when: docker_installed.failed 
      
      - name: Add Docker APT repository
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        when: docker_installed.failed 
      
      - name: Update apt package cache again
        apt:
          update_cache: yes
        when: docker_installed.failed 
      
      - name: Install Docker
        apt:
          name: docker-ce
          state: present
        when: docker_installed.failed 
      
      - name: Start and enable Docker service
        service:
          name: docker
          state: started
          enabled: yes
        when: docker_installed.failed 

      - name: Install Docker Compose
        command: >
          curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        args:
          creates: /usr/local/bin/docker-compose
        register: compose_download

      - name: Make Docker Compose executable
        command: chmod +x /usr/local/bin/docker-compose
        when: compose_download is succeeded

      - name: Confirm Docker and Docker Compose installation
        command: >
          docker --version && docker-compose --version
        register: dockerstatus
        changed_when: false
        
    - name: hostname
      shell: hostname
      register: hostname
    - name: Send the output with curl
      shell: |
        curl -X POST -H "Title: ansible task for server {{ hostname.stdout }}" -d "status {{ curlstatus.stdout }},{{ dockerstatus.stdout }}" https://ntfy.mmi-pt.com/ansible

