- name: Install server requirement
  hosts: all
  become: yes
  tasks:
    - name: Check if curl is installed (Debian-based systems)
      command: dpkg -l | grep curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Check if curl is installed (Red Hat-based systems)
      command: rpm -q curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Install curl (Debian-based systems)
      apt:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'Ubuntu'

    - name: Install curl (Red Hat-based systems)
      yum:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'CentOS'

    - name: Check if Docker is installed
      command: dpkg -l | grep -E '^ii' | grep -q docker
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker if not installed
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
      when: docker_installed.rc == 0
