- name: Install server requirement
  hosts: all
  become: yes
  tasks:
    - name: Check if curl is installed (Debian-based systems)
      command: dpkg -l | grep curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Check if curl is installed (Red Hat-based systems)
      command: rpm -q curl
      ignore_errors: yes
      register: curl_check
      changed_when: false

    - name: Install curl (Debian-based systems)
      apt:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'Ubuntu'

    - name: Install curl (Red Hat-based systems)
      yum:
        name: curl
        state: present
      when: curl_check.failed and ansible_distribution == 'CentOS'

      - name: Install Python pip
        apt: name={{ item }} update_cache=true state=present force_apt_get=yes
        with_items:
        - python-pip
        - python3-pip

      - name: Install Python packages
        pip: name={{ item }}
        with_items:
        - psycopg2-binary

      - name: install pexpect
        pip:
         name: pexpect
