---
- hosts: all
  connection: network_cli
  gather_facts: no 

  tasks:
  - name: Install Python pip
    apt: name={{ item }} update_cache=true state=present force_apt_get=yes
    with_items:
    - python-pip
    - python3-pip
    become: true
  - name: Install Python packages
    pip: name={{ item }}
    with_items:
    - psycopg2-binary
    become: true
  - name: install paramiko
    pip:
      name: paramiko
    become: yes

  - name: show ip address
    routeros_command:
      commands: ip address print
